#!/bin/env python
#
# http://stackoverflow.com/questions/7255885/save-dump-a-yaml-file-with-comments-in-pyyaml
#
# pip install ruamel.yaml
# https://pypi.python.org/pypi/ruamel.yaml
#
from __future__ import print_function

import os.path
from sys import argv

import datetime
import re

import ruamel.yaml as yaml

import json

opt_noop = False

datetime_encoder = lambda obj: (
    obj.isoformat()
    if isinstance(obj, datetime.datetime)
    or isinstance(obj, datetime.date)
    else None
)

def convert(a):
    print("normalize: ", a)
    fd = file(a, 'r')
    try:
        y = yaml.load(fd, yaml.RoundTripLoader)
    except yaml.YAMLError as e:
        print("ERROR: ", a, e)
        return
    finally:
        fd.close

    if y is None:
        #print("ERROR: ", a)
        return

    if opt_noop:
        return

    json_filename = re.sub('\.yaml', '.json', a)
    json_filename = re.sub('\.yml', '.json', a)
    if json_filename == a:
        print("ERROR: bogus filename: ", a)
        return

    fd = open(json_filename, 'w')
    s = json.dumps(y, default=datetime_encoder, sort_keys=True, indent=2)
    s = re.sub(' $', '', s, count=0, flags=re.MULTILINE)
    fd.write(s)
    fd.write('\n')
    fd.close()

def main(argv):
    if argv[1] == '--noop':
        opt_noop = True
        del argv[1]
    for a in argv[1:]:
        if os.path.isfile(a):
            convert(a)

if __name__ == "__main__":
    main(argv)
